[functions.player-headshot]
verify_jwt = false

[functions.nba-rosters]
verify_jwt = false

[functions.gleague-rosters]
verify_jwt = false

[functions.wnba-rosters]
verify_jwt = false

[functions.wnba-schedule]
verify_jwt = false

[functions.wnba-live-game]
verify_jwt = false

[functions.export-image]
verify_jwt = false
