export const STATIC_REFEREE_HEADSHOT_PATHS = `
referees/Aaron Smith.jpg
referees/Agon Abazi.jpg
referees/Amy Bonner.jpg
referees/Andy Nagy.jpg
referees/Angel Kent.jpg
referees/Angelica Suffren.jpg
referees/Ashley Gloss.jpg
referees/Ashley Moyer-Gleich.jpg
referees/Ben Taylor.jpg
referees/Bennie Adams.jpg
referees/Bill Kennedy.jpg
referees/Biniam Maru.jpg
referees/Blanca Burns.jpg
referees/Brandon Adair.jpg
referees/Brandon Schwab.jpg
referees/Brent Barnaky.jpg
referees/Brent Haskill.jpg
referees/Brett Nansel.jpg
referees/Brian Forte.jpg
referees/CJ Washington.jpeg
referees/CP Painter.jpg
referees/Cat Chang.jpg
referees/Charles Watson.jpg
referees/Che Flores.jpeg
referees/Chelisa Painter.jpg
referees/Clare Aubry.jpg
referees/Clare Simmons.jpg
referees/Courtney Kirkland.jpg
referees/Curtis Blair.jpg
referees/Danielle Scott.jpg
referees/Dannica Baroody.jpg
referees/Dannica Mosher.jpg
referees/David Guthrie.jpg
referees/Dedric Taylor.jpg
referees/Derek Richardson.jpg
referees/Derrick Collins.jpg
referees/Ed Malloy.jpg
referees/Eric Dalen.jpg
referees/Eric Lewis.jpg
referees/Evan Scott.jpg
referees/Fatou Cissoko-Stephens.jpg
referees/Gediminas Petraitis.jpg
referees/Genesis Perrymond.jpg
referees/Gerda Gatling.jpg
referees/Gina Catanzariti.jpeg
referees/Gina Cross.jpg
referees/Intae Hwang.jpg
referees/Isaac Barnett.jpg
referees/J.T. Orr.jpg
referees/JB DeRosa.jpg
referees/JD Ralls.jpg
referees/JT Orr.jpg
referees/Jacyn Goble.jpg
referees/James Capers.jpg
referees/James Williams.jpg
referees/Jason Alabanza.jpg
referees/Jason Goldenberg.jpg
referees/Jeff Wooten.jpg
referees/Jenna Reneau.jpg
referees/Jenna Schroeder.jpg
referees/John Butler.jpg
referees/John Conley.jpg
referees/John Goble.jpg
referees/Jonathan Sterling.jpg
referees/Josh Reed.jpg
referees/Josh Tiven.jpg
referees/Justin Van Duyne.jpg
referees/Karl Lane.jpg
referees/Kelly Broomfield.jpg
referees/Kelsey Reynolds.jpg
referees/Ken Jones.jpg
referees/Kevin Cutler.jpg
referees/Kevin Fahy.jpg
referees/Kevin Scott.jpg
referees/Klajdi Mulla.jpg
referees/Lauren Holtkamp-Sterling.jpg
referees/Leah Lanie.jpg
referees/Leon Wood.jpg
referees/Maj Forsberg.jpg
referees/Marat Kogut.jpg
referees/Marc Davis.jpg
referees/Marcy Williams.jpg
referees/Mark Lindsay.jpg
referees/Matt Boland.jpeg
referees/Matt Kallio.jpg
referees/Matt Myers.jpg
referees/Michael Smith.jpg
referees/Mitchell Ervin.jpg
referees/Mousa Dagher.jpg
referees/Natalie Sago.jpg
referees/Nate Cearley.jpg
referees/Nate Green.jpg
referees/Nick Buchert.jpg
referees/Pat Fraher.jpg
referees/Pat O'Connell.jpg
referees/Phenizee Ransom.jpg
referees/RJ Johnson.jpg
referees/Randy Richardson.jpg
referees/Ray Acosta.jpg
referees/Robert Hussey.jpg
referees/Rodney Mott.jpg
referees/Roy Gulbeyan.jpg
referees/Ryan Sassano.jpg
referees/Sarah Williams.jpg
referees/Scott Foster.jpg
referees/Scott Twardoski.jpg
referees/Scott Wall.jpeg
referees/Sean Corbin.jpeg
referees/Sean Wright.jpg
referees/Sha'Rae Mitchell.jpg
referees/Simone Jelks.jpg
referees/Suyash Mehta.jpg
referees/Teresa Stuck.jpg
referees/Tiara Cruse.jpg
referees/Tim Greene.jpg
referees/Tom Washington.jpg
referees/Toni Patillo.jpg
referees/Tony Brothers.jpg
referees/Tre Maddox.jpg
referees/Tyler Ford.jpg
referees/Tyler Mirkovich.jpg
referees/Tyler Ricks.jpg
referees/Zach Zarba.jpg
referees_review_duplicates/Agon Abazi.jpg
referees_review_duplicates/Marcy Williams.jpg
referees_review_duplicates/Tyler Mirkovich.jpg
`
  .trim()
  .split(/\n/)
  .map((path) => `./assets/${path.trim()}`);
